version: "3"
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.4.0-community
    hostname: sonarqube.mic.com.tw
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /data/sonarqube/sonarqube/data:/opt/sonarqube/data
      - /data/sonarqube/sonarqube/extensions:/opt/sonarqube/extensions
      - /data/sonarqube/sonarqube/logs:/opt/sonarqube/logs
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /data/sonarqube/postgresql/var:/var/lib/postgresql
      - /data/sonarqube/postgresql/data:/var/lib/postgresql/data
  nginx:
    container_name: nginx
    image: nginx:1.22.0
    hostname: nginx
    restart: always
    ports:
      - '10.88.27.19:80:80'
      - '10.88.27.19:443:443'
    volumes:
      - /data/sonarqube/nginx/http_ssl_certs:/etc/ssl/private
      - /data/sonarqube/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sonarqube
